### PR TITLE
fix cache for ft account balances

### LINKED ISSUE #194: Backend doesn't return user balances in Fungible Tokens
The issue occurs periodically in about half an hour after deploy.

### PR DESCRIPTION
**Pull request by thepiwo**
fixes #194

### CODE REVIEW

File: test/aeternity.js [hunk 1]
```diff
@@ -168,10 +168,8 @@ describe('Aeternity', () => {
       result.should.be.an('array');
       const [[address, balance]] = result;
       address.should.be.an('string');
-      balance.should.be.an('string');
+      balance.should.be.an('number');
       address.should.contain('ak_');
```
Comment (kenodressel) [inline test/aeternity.js:172]:
```suggestion
      address.should.contain('ak_');
      if (balance === 0) {
        balance.should.be.an('number');
      } else {
        balance.should.be.an('string');
        const intBalance = parseInt(balance, 10);
        intBalance.should.be.greaterThan(0);
      }
```

**Review by kenodressel — APPROVED** [review]
